#!/bin/bash

# Minimal SketchyBar config with Aerospace integration
# Catppuccin Mocha color scheme

PLUGIN_DIR="$CONFIG_DIR/plugins"

# Colors (Gruvbox Dark)
BAR_COLOR=0xff282828
ITEM_BG_COLOR=0xff3c3836
ACCENT_COLOR=0xfffabd2f
TEXT_COLOR=0xffebdbb2
ICON_COLOR=0xfffbf1c7

##### Bar Appearance #####
sketchybar --bar position=top \
                 height=28 \
                 blur_radius=0 \
                 color=$BAR_COLOR

##### Changing Defaults #####
default=(
  padding_left=4
  padding_right=4
  icon.font="SF Pro:Semibold:13.0"
  label.font="SF Pro:Regular:12.0"
  icon.color=$ICON_COLOR
  label.color=$TEXT_COLOR
  icon.padding_left=4
  icon.padding_right=4
  label.padding_left=4
  label.padding_right=4
)
sketchybar --default "${default[@]}"

##### Adding Aerospace Workspace Indicators #####
SPACE_ICONS=("1" "2" "3" "4" "5" "6" "7" "8" "9")
for i in "${!SPACE_ICONS[@]}"
do
  sid="$(($i+1))"
  sketchybar --add item space.$sid left \
             --set space.$sid icon="${SPACE_ICONS[i]}" \
                              icon.padding_left=8 \
                              icon.padding_right=8 \
                              background.color=$ITEM_BG_COLOR \
                              background.corner_radius=4 \
                              background.height=20 \
                              background.drawing=on \
                              label.drawing=off \
                              click_script="aerospace workspace $sid"
done

##### Adding Left Items #####
sketchybar --add item front_app left \
           --set front_app icon.drawing=off \
                           background.padding_left=8 \
                           script="$PLUGIN_DIR/front_app.sh" \
           --subscribe front_app front_app_switched

##### Adding Right Items #####
sketchybar --add item clock right \
           --set clock update_freq=10 \
                       icon= \
                       script="$PLUGIN_DIR/clock.sh" \
                       background.padding_right=4

sketchybar --add item battery right \
           --set battery update_freq=120 \
                         script="$PLUGIN_DIR/battery.sh" \
                         background.padding_right=8 \
           --subscribe battery system_woke power_source_change

##### Force all scripts to run the first time #####
sketchybar --update
